package com.a401.backend.global.enums;

public enum Subject {
    KOREAN, MATH, ENGLISH, KOREANHISTORY, LIFEANDETHICS, ETHICSANDIDEAS, KOREANGEOGRAPHY, WORLDGEOGRAPHY,
    EASTASIANHISTORY, WORLDHISTORY, POLITICSANDLAW, ECONOMY, SOCIETYANDCULTURE,
    PHYSICSI, CHEMISTRYI, LIFESCIENCEI, EARTHSCIENCEI, PHYSICSII, CHEMISTRYII,
    LIFESCIENCEII, EARTHSCIENCEII, GERMANI, FRENCHI, SPANISHI, CHINESEI,
    JAPANESEI, RUSSIANI, ARABICI, VIETNAMESEI, OLDCHINESEI
}
