// @ts-nocheck

import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import styled from '@emotion/styled';
import Navbar from '../component/Navbar';
import TimeLapse from '../component/home/TimeLapse';
import TodayMy from '../component/home/TodayMy';
import TopTimeLapse from '../component/home/TopTimeLapse';
import HomeCateSelect from '../component/home/HomeCateSelect';
import HomeVideoList from '../component/home/HomeVideoList';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Zzip_0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/home.png" />
      </Head>

      <main>
        <Navbar />
        <HomeContainer>
          <HomeCateSelect />
          <HomeVideoList />
        </HomeContainer>
      </main>
    </div>
  );
};

export default Home;

const HomeContainer = styled.div`
  display: flex;
  flex-direction: column;
`;
