server:
  port: 8000
  tomcat:
    remoteip:
      protocol-header: x-forwarded-proto
  servlet:
    context-path: /api/

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    # 로컬 버전
#    url: jdbc:mariadb://localhost:3306/a401?characterEncoding=UTF-8&serverTimezone=UTC

    # aws 테스트 디비 버전
    url: jdbc:mariadb://k7a401.p.ssafy.io:3306/localtest?characterEncoding=UTF-8&serverTimezone=UTC

    # 찐 aws 디비
#    url: jdbc:mariadb://k7a401.p.ssafy.io:3306/a401?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${DBuser}
    password: ${DBpassword}
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
  security:
    oauth2:
      client:
        registration:
          google: # /oauth2/authorization/google 이 주소를 동작하게 한다.
            #client-id: 997477992148-ritut3glnv9d6o95p452tptvvq0tc7l5.apps.googleusercontent.com
            client-id: 944190037169-3c3jb5nchoosjcnf47ddgoovu09rnrat.apps.googleusercontent.com
            #client-secret: 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
            client-secret: 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
            redirectUri: "https://zzip0.com/api/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG

app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080,https://zzip0.com,https://zzip0.com/api
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      # local테스트
      # - http://localhost:3000/oauth2/redirect
      # 배포 버전
      - https://zzip0.com/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect

cloud:
  aws:
    credentials:
      instance-profile: true
      access-key: ${S3access}
      secret-key: ${S3secret}
    s3:
      bucket: a401
    region:
      static: ap-northeast-2
    stack:
      auto: false

